### ISSUE TITLE
Call to undefined function Safe\date()

### ISSUE THREAD

**Issue by FinlayDaG33k** [WyriHaximus/reactphp-cron#28]
Hii there,

I'm trying to implement this library into my app but I get an error that the function "Safe\date()" is undefined, which causes errors (see stacktrace).  
I have tried looking for "Safe\date()" manually, but can't seem to find it anywhere.

```
PHP Fatal error:  Uncaught Error: Call to undefined function Safe\date() in F:\repos\FinlayDaG33k\yuuki\vendor\wyrihaximus\react-cron\src\Cron\Scheduler.php:86
Stack trace:
#0 F:\repos\FinlayDaG33k\yuuki\vendor\wyrihaximus\react-cron\src\Cron\Scheduler.php(38): WyriHaximus\React\Cron\Scheduler->align()
#1 F:\repos\FinlayDaG33k\yuuki\vendor\wyrihaximus\react-cron\src\Cron.php(27): WyriHaximus\React\Cron\Scheduler->__construct(Object(Amp\ReactAdapter\ReactAdapter))
#2 F:\repos\FinlayDaG33k\yuuki\vendor\wyrihaximus\react-cron\src\Cron.php(38): WyriHaximus\React\Cron->__construct(Object(Amp\ReactAdapter\ReactAdapter), Object(WyriHaximus\React\Mutex\Memory), Object(WyriHaximus\React\Cron\Action))
#3 F:\repos\FinlayDaG33k\yuuki\src\Monitor\DayscheduleMonitor.php(22): WyriHaximus\React\Cron::create(Object(Amp\ReactAdapter\ReactAdapter), Object(WyriHaximus\React\Cron\Action))
#4 F:\repos\FinlayDaG33k\yuuki\src\Yuuki.php(39): Yuuki\Monitor\DayscheduleMonitor->__construct()
#5 F:\repos\FinlayDaG33k\yuuki\vendor\amphp\amp\lib\Loop\Driver in F:\repos\FinlayDaG33k\yuuki\vendor\wyrihaximus\react-cron\src\Cron\Scheduler.php on line 86
```

**Comment by WyriHaximus** [comment]
Just tagged a new release fixing this, thank you for reporting :+1:
